### ISSUE TITLE
训练损失一直很高，准确度不足1%，是我命令行里的参数输入有问题吗

### ISSUE THREAD

**Issue by leo-lab-511** [znchen666/HDG#1]
训练损失一直很高，准确度不足1%，是我命令行里的参数输入有问题吗
python train.py --seed 0 --lr 1e-3 --data_dir D:/leo/HDG-main/OfficeHome/ --domain_num 4 --max_epoch 50 --net resnet18 --task img_dg --output D:\leo\HDG-main\output --test_envs 0 --dataset office-home --algorithm SCIPD --steps_per_epoch 100 --gpu_id 0 --is_different_class_space 0 --is_data_aug yes --loader_name daml_loader --is_different_class_space 0

**Comment by X-funbean** [comment]
Hi, can you reproduce the results with the provided codes? @leo-lab-511
